<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace IndexEngine\Model;

use IndexEngine\Model\Base\IndexEngineIndexTemplate as BaseIndexEngineIndexTemplate;
use Thelia\Model\Tools\ModelEventDispatcherTrait;

/**
 * Class IndexEngineIndexTemplate
 * @package IndexEngine\Model
 */
class IndexEngineIndexTemplate extends BaseIndexEngineIndexTemplate
{
    use ModelEventDispatcherTrait;

    public function getConditions()
    {
        return json_decode(base64_decode($this->getSerializedCondition()), true);
    }

    public function setConditions(array $conditions)
    {
        return $this->setSerializedCondition(base64_encode(json_encode($conditions)));
    }

    public function getColumns()
    {
        return json_decode(base64_decode($this->getSerializedColumns()), true);
    }

    public function setColumns(array $columns)
    {
        return $this->setSerializedColumns(base64_encode(json_encode($columns)));
    }
}
