<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace IndexEngine\Model;

use IndexEngine\Model\Base\IndexEngineIndex as BaseIndexEngineIndex;
use Thelia\Model\Tools\ModelEventDispatcherTrait;

/**
 * Class IndexEngineIndex
 * @package IndexEngine\Model
 */
class IndexEngineIndex extends BaseIndexEngineIndex
{
    use ModelEventDispatcherTrait;

    public function getConditions()
    {
        $data = json_decode(base64_decode($this->getSerializedCondition()), true);

        if (null === $data) {
            $data = [];
        }

        return $data;
    }

    public function setConditions(array $conditions)
    {
        return $this->setSerializedCondition(base64_encode(json_encode($conditions)));
    }

    public function getColumns()
    {
        $data = json_decode(base64_decode($this->getSerializedColumns()), true);

        if (null === $data) {
            $data = [];
        }

        return $data;
    }

    public function setColumns(array $columns)
    {
        return $this->setSerializedColumns(base64_encode(json_encode($columns)));
    }
}
