<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace IndexEngine\Model;

use IndexEngine\Model\Base\IndexEngineIndexTemplate as BaseIndexEngineIndexTemplate;
use Thelia\Model\Tools\ModelEventDispatcherTrait;

/**
 * Class IndexEngineIndexTemplate
 * @package IndexEngine\Model
 */
class IndexEngineIndexTemplate extends BaseIndexEngineIndexTemplate
{
    use ModelEventDispatcherTrait;
}
