<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace IndexEngine\Model;

use IndexEngine\Model\Base\IndexEngineIndex as BaseIndexEngineIndex;
use Thelia\Model\Tools\ModelEventDispatcherTrait;

/**
 * Class IndexEngineIndex
 * @package IndexEngine\Model
 */
class IndexEngineIndex extends BaseIndexEngineIndex
{
    use ModelEventDispatcherTrait;
}
