<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace IndexEngine\Action;

use IndexEngine\Action\Base\IndexEngineDriverConfigurationAction as  BaseIndexEngineDriverConfigurationAction;

/**
 * Class IndexEngineDriverConfigurationAction
 * @package IndexEngine\Action
 */
class IndexEngineDriverConfigurationAction extends BaseIndexEngineDriverConfigurationAction
{
}
