<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace IndexEngine\Action;

use IndexEngine\Action\Base\IndexEngineIndexTemplateAction as  BaseIndexEngineIndexTemplateAction;

/**
 * Class IndexEngineIndexTemplateAction
 * @package IndexEngine\Action
 */
class IndexEngineIndexTemplateAction extends BaseIndexEngineIndexTemplateAction
{
}
