<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace IndexEngine\Action;

use IndexEngine\Action\Base\IndexEngineIndexAction as  BaseIndexEngineIndexAction;
use IndexEngine\Event\IndexEngineIndexEvent;

/**
 * Class IndexEngineIndexAction
 * @package IndexEngine\Action
 */
class IndexEngineIndexAction extends BaseIndexEngineIndexAction
{
    public function create(IndexEngineIndexEvent $event)
    {
        $event->setSerializedColumns("");
        $event->setSerializedCondition("");
        $event->setType("");
        $event->setEntity("");

        parent::create($event);
    }
}
