<?php
/**
 * This class has been generated by TheliaStudio
 * For more information, see https://github.com/thelia-modules/TheliaStudio
 */

namespace IndexEngine\Action;

use IndexEngine\Action\Base\IndexEngineDriverConfigurationAction as  BaseIndexEngineDriverConfigurationAction;
use IndexEngine\Event\IndexEngineDriverConfigurationEvent;
use IndexEngine\Model\IndexEngineDriverConfiguration;

/**
 * Class IndexEngineDriverConfigurationAction
 * @package IndexEngine\Action
 */
class IndexEngineDriverConfigurationAction extends BaseIndexEngineDriverConfigurationAction
{
    protected function createOrUpdate(IndexEngineDriverConfigurationEvent $event, IndexEngineDriverConfiguration $model)
    {
        $parameters = $event->dumpParameters();

        // Clear thelia extra fields
        $this
            ->removeKey($parameters, "success_url")
            ->removeKey($parameters, "error_message")
        ;

        $model->setConfiguration($parameters);

        return parent::createOrUpdate($event, $model);
    }

    protected function removeKey(array &$array, $key)
    {
        if (array_key_exists($key, $array)) {
            unset($array[$key]);
        }

        return $this;
    }
}
