<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace IndexEngine\Form\Type;

use IndexEngine\Form\Type\Base\IndexEngineIndexTemplateIdType as BaseIndexEngineIndexTemplateIdType;

/**
 * Class IndexEngineIndexTemplate
 * @package IndexEngine\Form
 */
class IndexEngineIndexTemplateIdType extends BaseIndexEngineIndexTemplateIdType
{
}
