<?php
/**
 * This class has been generated by TheliaStudio
 * For more information, see https://github.com/thelia-modules/TheliaStudio
 */

namespace IndexEngine\Form\Type;

use IndexEngine\Form\Type\Base\IndexEngineDriverConfigurationIdType as BaseIndexEngineDriverConfigurationIdType;

/**
 * Class IndexEngineDriverConfiguration
 * @package IndexEngine\Form
 */
class IndexEngineDriverConfigurationIdType extends BaseIndexEngineDriverConfigurationIdType
{
}
