<?php
/**
 * This class has been generated by TheliaStudio
 * For more information, see https://github.com/thelia-modules/TheliaStudio
 */

namespace IndexEngine\Form\Type;

use IndexEngine\Form\Type\Base\IndexEngineIndexIdType as BaseIndexEngineIndexIdType;

/**
 * Class IndexEngineIndex
 * @package IndexEngine\Form
 */
class IndexEngineIndexIdType extends BaseIndexEngineIndexIdType
{
}
