<?php
/**
 * This class has been generated by TheliaStudio
 * For more information, see https://github.com/thelia-modules/TheliaStudio
 */

namespace IndexEngine\Event;

use IndexEngine\Event\Base\IndexEngineIndexEvent as BaseIndexEngineIndexEvent;

/**
 * Class IndexEngineIndexEvent
 * @package IndexEngine\Event
 */
class IndexEngineIndexEvent extends BaseIndexEngineIndexEvent
{
    private $conditions = array();
    private $columns = array();
    private $mapping = array();

    /**
     * @return array
     */
    public function getConditions()
    {
        return $this->conditions;
    }

    /**
     * @param  array $conditions
     * @return $this
     */
    public function setConditions(array $conditions)
    {
        $this->conditions = $conditions;

        return $this;
    }

    /**
     * @return array
     */
    public function getColumns()
    {
        return $this->columns;
    }

    /**
     * @param  array $columns
     * @return $this
     */
    public function setColumns(array $columns)
    {
        $this->columns = $columns;

        return $this;
    }

    /**
     * @param $name
     * @param $value
     * @return $this
     */
    public function addCondition($name, $value)
    {
        $this->conditions[$name] = $value;

        return $this;
    }

    public function getCondition($name, $default = null)
    {
        if (isset($this->conditions[$name])) {
            return $this->conditions [$name];
        }

        return $default;
    }

    /**
     * @deprecated
     */
    public function getSerializedColumns()
    {
        return;
    }

    /**
     * @deprecated
     */
    public function getSerializedCondition()
    {
        return;
    }

    /**
     * @return array
     */
    public function getMapping()
    {
        return $this->mapping;
    }

    /**
     * @param  array $mapping
     * @return $this
     */
    public function setMapping(array $mapping)
    {
        $this->mapping = $mapping;

        return $this;
    }
}
