<?php
/**
 * This class has been generated by TheliaStudio
 * For more information, see https://github.com/thelia-modules/TheliaStudio
 */

namespace IndexEngine\Event;

use IndexEngine\Event\Base\IndexEngineDriverConfigurationEvents as BaseIndexEngineDriverConfigurationEvents;

/**
 * Class IndexEngineDriverConfigurationEvents
 * @package IndexEngine\Event
 */
class IndexEngineDriverConfigurationEvents extends BaseIndexEngineDriverConfigurationEvents
{
}
