<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace IndexEngine\Event;

use IndexEngine\Event\Base\IndexEngineIndexTemplateEvents as BaseIndexEngineIndexTemplateEvents;

/**
 * Class IndexEngineIndexTemplateEvents
 * @package IndexEngine\Event
 */
class IndexEngineIndexTemplateEvents extends BaseIndexEngineIndexTemplateEvents
{
}
