<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace IndexEngine\Event;

use IndexEngine\Event\Base\IndexEngineIndexTemplateEvent as BaseIndexEngineIndexTemplateEvent;

/**
 * Class IndexEngineIndexTemplateEvent
 * @package IndexEngine\Event
 */
class IndexEngineIndexTemplateEvent extends BaseIndexEngineIndexTemplateEvent
{
}
