<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace IndexEngine\Event;

use IndexEngine\Event\Base\IndexEngineIndexEvent as BaseIndexEngineIndexEvent;

/**
 * Class IndexEngineIndexEvent
 * @package IndexEngine\Event
 */
class IndexEngineIndexEvent extends BaseIndexEngineIndexEvent
{
}
