<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace IndexEngine\Event;

use IndexEngine\Event\Base\IndexEngineIndexEvents as BaseIndexEngineIndexEvents;

/**
 * Class IndexEngineIndexEvents
 * @package IndexEngine\Event
 */
class IndexEngineIndexEvents extends BaseIndexEngineIndexEvents
{
    const RENDER_CONFIGURATION_TEMPLATE = "index_engine.render_configuration_template";

    const RENDER_CONFIGURATION_COLUMNS_TEMPLATE = "index_engine.render_configuration_template.columns";
}
