<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace IndexEngine\Form\Base;

use IndexEngine\IndexEngine;
use Thelia\Form\BaseForm;
use Symfony\Component\Validator\Constraints\NotBlank;

/**
 * Class IndexEngineDriverConfigurationCreateForm
 * @package IndexEngine\Form\Base
 * @author TheliaStudio
 */
class IndexEngineDriverConfigurationCreateForm extends BaseForm
{
    const FORM_NAME = "index_engine_driver_configuration_create";

    public function buildForm()
    {
        $translationKeys = $this->getTranslationKeys();
        $fieldsIdKeys = $this->getFieldsIdKeys();

        $this->addDriverCodeField($translationKeys, $fieldsIdKeys);
        $this->addTitleField($translationKeys, $fieldsIdKeys);
        $this->addSerializedConfigurationField($translationKeys, $fieldsIdKeys);
    }

    protected function addDriverCodeField(array $translationKeys, array $fieldsIdKeys)
    {
        $this->formBuilder->add("driver_code", "text", array(
            "label" => $this->translator->trans($this->readKey("driver_code", $translationKeys), [], IndexEngine::MESSAGE_DOMAIN),
            "label_attr" => ["for" => $this->readKey("driver_code", $fieldsIdKeys)],
            "required" => true,
            "constraints" => array(
                new NotBlank(),
            ),
            "attr" => array(
            )
        ));
    }

    protected function addTitleField(array $translationKeys, array $fieldsIdKeys)
    {
        $this->formBuilder->add("title", "text", array(
            "label" => $this->translator->trans($this->readKey("title", $translationKeys), [], IndexEngine::MESSAGE_DOMAIN),
            "label_attr" => ["for" => $this->readKey("title", $fieldsIdKeys)],
            "required" => true,
            "constraints" => array(
                new NotBlank(),
            ),
            "attr" => array(
            )
        ));
    }

    protected function addSerializedConfigurationField(array $translationKeys, array $fieldsIdKeys)
    {
        $this->formBuilder->add("serialized_configuration", "textarea", array(
            "label" => $this->translator->trans($this->readKey("serialized_configuration", $translationKeys), [], IndexEngine::MESSAGE_DOMAIN),
            "label_attr" => ["for" => $this->readKey("serialized_configuration", $fieldsIdKeys)],
            "required" => true,
            "constraints" => array(
                new NotBlank(),
            ),
            "attr" => array(
            )
        ));
    }

    public function getName()
    {
        return static::FORM_NAME;
    }

    public function readKey($key, array $keys, $default = '')
    {
        if (isset($keys[$key])) {
            return $keys[$key];
        }

        return $default;
    }

    public function getTranslationKeys()
    {
        return array();
    }

    public function getFieldsIdKeys()
    {
        return array(
            "driver_code" => "index_engine_driver_configuration_driver_code",
            "title" => "index_engine_driver_configuration_title",
            "serialized_configuration" => "index_engine_driver_configuration_serialized_configuration",
        );
    }
}
