<?php
/**
 * This class has been generated by TheliaStudio
 * For more information, see https://github.com/thelia-modules/TheliaStudio
 */

namespace IndexEngine\Form\Base;

use IndexEngine\Form\IndexEngineDriverConfigurationCreateForm as ChildIndexEngineDriverConfigurationCreateForm;
use IndexEngine\Form\Type\IndexEngineDriverConfigurationIdType;

/**
 * Class IndexEngineDriverConfigurationForm
 * @package IndexEngine\Form
 * @author TheliaStudio
 */
class IndexEngineDriverConfigurationUpdateForm extends ChildIndexEngineDriverConfigurationCreateForm
{
    const FORM_NAME = "index_engine_driver_configuration_update";

    public function buildForm()
    {
        parent::buildForm();

        $this->formBuilder
            ->add("id", IndexEngineDriverConfigurationIdType::TYPE_NAME)
        ;
    }
}
