<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace IndexEngine\Form\Base;

use IndexEngine\Form\IndexEngineIndexTemplateCreateForm as ChildIndexEngineIndexTemplateCreateForm;
use IndexEngine\Form\Type\IndexEngineIndexTemplateIdType;

/**
 * Class IndexEngineIndexTemplateForm
 * @package IndexEngine\Form
 * @author TheliaStudio
 */
class IndexEngineIndexTemplateUpdateForm extends ChildIndexEngineIndexTemplateCreateForm
{
    const FORM_NAME = "index_engine_index_template_update";

    public function buildForm()
    {
        parent::buildForm();

        $this->formBuilder
            ->add("id", IndexEngineIndexTemplateIdType::TYPE_NAME)
            ->remove("visible")
        ;
    }
}
