<?php
/**
 * This class has been generated by TheliaStudio
 * For more information, see https://github.com/thelia-modules/TheliaStudio
 */

namespace IndexEngine\Form\Base;

use IndexEngine\Form\IndexEngineIndexCreateForm as ChildIndexEngineIndexCreateForm;
use IndexEngine\Form\Type\IndexEngineIndexIdType;

/**
 * Class IndexEngineIndexForm
 * @package IndexEngine\Form
 * @author TheliaStudio
 */
class IndexEngineIndexUpdateForm extends ChildIndexEngineIndexCreateForm
{
    const FORM_NAME = "index_engine_index_update";

    public function buildForm()
    {
        parent::buildForm();

        $this->formBuilder
            ->add("id", IndexEngineIndexIdType::TYPE_NAME)
            ->remove("visible")
        ;
    }
}
