<?php
/**
 * This class has been generated by TheliaStudio
 * For more information, see https://github.com/thelia-modules/TheliaStudio
 */

namespace IndexEngine\Loop;

use IndexEngine\Loop\Base\IndexEngineDriverConfiguration as BaseIndexEngineDriverConfigurationLoop;

/**
 * Class IndexEngineDriverConfiguration
 * @package IndexEngine\Loop
 */
class IndexEngineDriverConfiguration extends BaseIndexEngineDriverConfigurationLoop
{
    /**
 * You may now add your own logic
 */
}
