<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace IndexEngine\Loop;

use IndexEngine\Loop\Base\IndexEngineIndex as BaseIndexEngineIndexLoop;

/**
 * Class IndexEngineIndex
 * @package IndexEngine\Loop
 */
class IndexEngineIndex extends BaseIndexEngineIndexLoop
{
    /**
     * You may now add your own logic
     */
}
