<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace IndexEngine\Loop;

use IndexEngine\Loop\Base\IndexEngineIndexTemplate as BaseIndexEngineIndexTemplateLoop;

/**
 * Class IndexEngineIndexTemplate
 * @package IndexEngine\Loop
 */
class IndexEngineIndexTemplate extends BaseIndexEngineIndexTemplateLoop
{
    /**
     * You may now add your own logic
     */
}
