<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace IndexEngine\Form;

use IndexEngine\Form\Base\IndexEngineDriverConfigurationUpdateForm as BaseIndexEngineDriverConfigurationUpdateForm;

/**
 * Class IndexEngineDriverConfigurationUpdateForm
 * @package IndexEngine\Form
 */
class IndexEngineDriverConfigurationUpdateForm extends BaseIndexEngineDriverConfigurationUpdateForm
{
    public function getTranslationKeys()
    {
        return array(
            "id" => "id",
            "driver_code" => "driver_code",
            "title" => "title",
            "serialized_configuration" => "serialized_configuration",
        );
    }
}
