<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace IndexEngine\Form;

use IndexEngine\Form\Base\IndexEngineDriverConfigurationCreateForm as BaseIndexEngineDriverConfigurationCreateForm;
use IndexEngine\IndexEngine;
use Symfony\Component\Validator\Constraints\NotBlank;

/**
 * Class IndexEngineDriverConfigurationCreateForm
 * @package IndexEngine\Form
 */
class IndexEngineDriverConfigurationCreateForm extends BaseIndexEngineDriverConfigurationCreateForm
{
    public function buildForm()
    {
        parent::buildForm();

        $this->formBuilder
            ->add("driver_code", "index_engine_driver", [
                "label" => $this->translator->trans("Driver", [], IndexEngine::MESSAGE_DOMAIN),
                "label_attr" => ["for" => "index_engine_driver"],
                "required" => true,
                "constraints" => [
                    new NotBlank(),
                ]
            ]);
    }

    public function getTranslationKeys()
    {
        return array(
            "driver_code" => "Driver code",
            "title" => "Title",
        );
    }

    protected function addSerializedConfigurationField(array $translationKeys, array $fieldsIdKeys)
    {
        // Remove this field
    }

    protected function addDriverCodeField(array $translationKeys, array $fieldsIdKeys)
    {
        // Remove this field
    }
}
