<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace IndexEngine\Form;

use IndexEngine\Form\Base\IndexEngineIndexUpdateForm as BaseIndexEngineIndexUpdateForm;

/**
 * Class IndexEngineIndexUpdateForm
 * @package IndexEngine\Form
 */
class IndexEngineIndexUpdateForm extends BaseIndexEngineIndexUpdateForm
{
    public function getTranslationKeys()
    {
        return array(
            "id" => "id",
            "visible" => "visible",
            "code" => "code",
            "title" => "title",
            "entity" => "entity",
            "serialized_columns" => "serialized_columns",
            "serialized_condition" => "serialized_condition",
            "index_engine_driver_configuration_id" => "index_engine_driver_configuration_id",
        );
    }
}
