<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace IndexEngine\Form;

use IndexEngine\Form\Base\IndexEngineIndexTemplateCreateForm as BaseIndexEngineIndexTemplateCreateForm;

/**
 * Class IndexEngineIndexTemplateCreateForm
 * @package IndexEngine\Form
 */
class IndexEngineIndexTemplateCreateForm extends BaseIndexEngineIndexTemplateCreateForm
{
    public function getTranslationKeys()
    {
        return array(
            "visible" => "Visible",
            "code" => "Code",
            "title" => "Title",
            "entity" => "Entity",
            "serialized_columns" => "Serialized columns",
            "serialized_condition" => "Serialized condition",
            "index_engine_driver_configuration_id" => "Index engine driver configuration id",
        );
    }
}
