<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace IndexEngine\Form;

use IndexEngine\Form\Base\IndexEngineDriverConfigurationCreateForm as BaseIndexEngineDriverConfigurationCreateForm;

/**
 * Class IndexEngineDriverConfigurationCreateForm
 * @package IndexEngine\Form
 */
class IndexEngineDriverConfigurationCreateForm extends BaseIndexEngineDriverConfigurationCreateForm
{
    public function getTranslationKeys()
    {
        return array(
            "driver_code" => "Driver code",
            "title" => "Title",
            "serialized_configuration" => "Serialized configuration",
        );
    }
}
