<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace IndexEngine\Form;

use IndexEngine\Form\Base\IndexEngineIndexCreateForm as BaseIndexEngineIndexCreateForm;

/**
 * Class IndexEngineIndexCreateForm
 * @package IndexEngine\Form
 */
class IndexEngineIndexCreateForm extends BaseIndexEngineIndexCreateForm
{
    public function getTranslationKeys()
    {
        return array(
            "visible" => "Visible",
            "code" => "Code",
            "title" => "Title",
            "entity" => "Entity",
            "index_engine_driver_configuration_id" => "Index engine driver configuration",
        );
    }
}
