<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace IndexEngine\Loop\Base;

use Propel\Runtime\ActiveQuery\Criteria;
use Thelia\Core\Template\Element\BaseLoop;
use Thelia\Core\Template\Element\LoopResult;
use Thelia\Core\Template\Element\LoopResultRow;
use Thelia\Core\Template\Element\PropelSearchLoopInterface;
use Thelia\Core\Template\Loop\Argument\Argument;
use Thelia\Core\Template\Loop\Argument\ArgumentCollection;
use Thelia\Type\BooleanOrBothType;
use \IndexEngineIndexTemplateQuery;

/**
 * Class IndexEngineIndexTemplate
 * @package IndexEngine\Loop\Base
 * @author TheliaStudio
 */
class IndexEngineIndexTemplate extends BaseLoop implements PropelSearchLoopInterface
{
    protected $timestampable = true;
    protected $versionable = true;

    /**
     * @param LoopResult $loopResult
     *
     * @return LoopResult
     */
    public function parseResults(LoopResult $loopResult)
    {
        /** @var \\IndexEngineIndexTemplate $entry */
        foreach ($loopResult->getResultDataCollection() as $entry) {
            $row = new LoopResultRow($entry);

            $row
                ->set("ID", $entry->getId())
                ->set("VISIBLE", $entry->getVisible())
                ->set("CODE", $entry->getCode())
                ->set("TITLE", $entry->getTitle())
                ->set("ENTITY", $entry->getEntity())
                ->set("SERIALIZED_COLUMNS", $entry->getSerializedColumns())
                ->set("SERIALIZED_CONDITION", $entry->getSerializedCondition())
                ->set("INDEX_ENGINE_DRIVER_CONFIGURATION_ID", $entry->getIndexEngineDriverConfigurationId())
            ;

            $this->addMoreResults($row, $entry);

            $loopResult->addRow($row);
        }

        return $loopResult;
    }

    /**
     * Definition of loop arguments
     *
     * example :
     *
     * public function getArgDefinitions()
     * {
     *  return new ArgumentCollection(
     *
     *       Argument::createIntListTypeArgument('id'),
     *           new Argument(
     *           'ref',
     *           new TypeCollection(
     *               new Type\AlphaNumStringListType()
     *           )
     *       ),
     *       Argument::createIntListTypeArgument('category'),
     *       Argument::createBooleanTypeArgument('new'),
     *       ...
     *   );
     * }
     *
     * @return \Thelia\Core\Template\Loop\Argument\ArgumentCollection
     */
    protected function getArgDefinitions()
    {
        return new ArgumentCollection(
            Argument::createIntListTypeArgument("id"),
            Argument::createBooleanOrBothTypeArgument("visible", BooleanOrBothType::ANY),
            Argument::createAnyTypeArgument("code"),
            Argument::createAnyTypeArgument("title"),
            Argument::createAnyTypeArgument("entity"),
            Argument::createIntListTypeArgument("index_engine_driver_configuration_id"),
            Argument::createEnumListTypeArgument(
                "order",
                [
                    "id",
                    "id-reverse",
                    "visible",
                    "visible-reverse",
                    "code",
                    "code-reverse",
                    "title",
                    "title-reverse",
                    "entity",
                    "entity-reverse",
                    "serialized_columns",
                    "serialized_columns-reverse",
                    "serialized_condition",
                    "serialized_condition-reverse",
                    "index_engine_driver_configuration_id",
                    "index_engine_driver_configuration_id-reverse",
                ],
                "id"
            )
        );
    }

    /**
     * this method returns a Propel ModelCriteria
     *
     * @return \Propel\Runtime\ActiveQuery\ModelCriteria
     */
    public function buildModelCriteria()
    {
        $query = new IndexEngineIndexTemplateQuery();

        if (null !== $id = $this->getId()) {
            $query->filterById($id);
        }

        if (BooleanOrBothType::ANY !== $visible = $this->getVisible()) {
            $query->filterByVisible($visible);
        }

        if (null !== $code = $this->getCode()) {
            $code = array_map("trim", explode(",", $code));
            $query->filterByCode($code);
        }

        if (null !== $title = $this->getTitle()) {
            $title = array_map("trim", explode(",", $title));
            $query->filterByTitle($title);
        }

        if (null !== $entity = $this->getEntity()) {
            $entity = array_map("trim", explode(",", $entity));
            $query->filterByEntity($entity);
        }

        if (null !== $index_engine_driver_configuration_id = $this->getIndexEngineDriverConfigurationId()) {
            $query->filterByIndexEngineDriverConfigurationId($index_engine_driver_configuration_id);
        }

        foreach ($this->getOrder() as $order) {
            switch ($order) {
                case "id":
                    $query->orderById();
                    break;
                case "id-reverse":
                    $query->orderById(Criteria::DESC);
                    break;
                case "visible":
                    $query->orderByVisible();
                    break;
                case "visible-reverse":
                    $query->orderByVisible(Criteria::DESC);
                    break;
                case "code":
                    $query->orderByCode();
                    break;
                case "code-reverse":
                    $query->orderByCode(Criteria::DESC);
                    break;
                case "title":
                    $query->orderByTitle();
                    break;
                case "title-reverse":
                    $query->orderByTitle(Criteria::DESC);
                    break;
                case "entity":
                    $query->orderByEntity();
                    break;
                case "entity-reverse":
                    $query->orderByEntity(Criteria::DESC);
                    break;
                case "serialized_columns":
                    $query->orderBySerializedColumns();
                    break;
                case "serialized_columns-reverse":
                    $query->orderBySerializedColumns(Criteria::DESC);
                    break;
                case "serialized_condition":
                    $query->orderBySerializedCondition();
                    break;
                case "serialized_condition-reverse":
                    $query->orderBySerializedCondition(Criteria::DESC);
                    break;
                case "index_engine_driver_configuration_id":
                    $query->orderByIndexEngineDriverConfigurationId();
                    break;
                case "index_engine_driver_configuration_id-reverse":
                    $query->orderByIndexEngineDriverConfigurationId(Criteria::DESC);
                    break;
            }
        }

        return $query;
    }

    protected function addMoreResults(LoopResultRow $row, $entryObject)
    {
    }
}
