<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace IndexEngine\Event\Base;

use IndexEngine\Event\Module\IndexEngineEvents as ChildIndexEngineEvents;

/*
 * Class IndexEngineIndexTemplateEvents
 * @package IndexEngine\Event\Base
 * @author TheliaStudio
 */
class IndexEngineIndexTemplateEvents
{
    const CREATE = ChildIndexEngineEvents::INDEX_ENGINE_INDEX_TEMPLATE_CREATE;
    const UPDATE = ChildIndexEngineEvents::INDEX_ENGINE_INDEX_TEMPLATE_UPDATE;
    const DELETE = ChildIndexEngineEvents::INDEX_ENGINE_INDEX_TEMPLATE_DELETE;
    const TOGGLE_VISIBILITY = ChildIndexEngineEvents::INDEX_ENGINE_INDEX_TEMPLATE_TOGGLE_VISIBILITY;
}
