<?php
/**
 * This class has been generated by TheliaStudio
 * For more information, see https://github.com/thelia-modules/TheliaStudio
 */

namespace IndexEngine\Event\Base;

use IndexEngine\Event\Module\IndexEngineEvents as ChildIndexEngineEvents;

/*
 * Class IndexEngineDriverConfigurationEvents
 * @package IndexEngine\Event\Base
 * @author TheliaStudio
 */
class IndexEngineDriverConfigurationEvents
{
    const CREATE = ChildIndexEngineEvents::INDEX_ENGINE_DRIVER_CONFIGURATION_CREATE;
    const UPDATE = ChildIndexEngineEvents::INDEX_ENGINE_DRIVER_CONFIGURATION_UPDATE;
    const DELETE = ChildIndexEngineEvents::INDEX_ENGINE_DRIVER_CONFIGURATION_DELETE;
}
