<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace IndexEngine\Event\Base;

use IndexEngine\Event\Module\IndexEngineEvents as ChildIndexEngineEvents;

/*
 * Class IndexEngineIndexEvents
 * @package IndexEngine\Event\Base
 * @author TheliaStudio
 */
class IndexEngineIndexEvents
{
    const CREATE = ChildIndexEngineEvents::INDEX_ENGINE_INDEX_CREATE;
    const UPDATE = ChildIndexEngineEvents::INDEX_ENGINE_INDEX_UPDATE;
    const DELETE = ChildIndexEngineEvents::INDEX_ENGINE_INDEX_DELETE;
    const TOGGLE_VISIBILITY = ChildIndexEngineEvents::INDEX_ENGINE_INDEX_TOGGLE_VISIBILITY;
}
