<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace IndexEngine\Form\Type\Base;

use Thelia\Core\Form\Type\Field\AbstractIdType;
use IndexEngine\Model\IndexEngineDriverConfigurationQuery;

/**
 * Class IndexEngineDriverConfiguration
 * @package IndexEngine\Form\Base
 * @author TheliaStudio
 */
class IndexEngineDriverConfigurationIdType extends AbstractIdType
{
    const TYPE_NAME = "index_engine_driver_configuration_id";

    protected function getQuery()
    {
        return new IndexEngineDriverConfigurationQuery();
    }

    public function getName()
    {
        return static::TYPE_NAME;
    }
}
