<?php
/**
 * This class has been generated by TheliaStudio
 * For more information, see https://github.com/thelia-modules/TheliaStudio
 */

namespace IndexEngine\Form\Type\Base;

use Thelia\Core\Form\Type\Field\AbstractIdType;
use IndexEngine\Model\IndexEngineIndexQuery;

/**
 * Class IndexEngineIndex
 * @package IndexEngine\Form\Base
 * @author TheliaStudio
 */
class IndexEngineIndexIdType extends AbstractIdType
{
    const TYPE_NAME = "index_engine_index_id";

    protected function getQuery()
    {
        return new IndexEngineIndexQuery();
    }

    public function getName()
    {
        return static::TYPE_NAME;
    }
}
