<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace IndexEngine\Controller;

use IndexEngine\Controller\Base\IndexEngineIndexTemplateController as BaseIndexEngineIndexTemplateController;

/**
 * Class IndexEngineIndexTemplateController
 * @package IndexEngine\Controller
 */
class IndexEngineIndexTemplateController extends BaseIndexEngineIndexTemplateController
{
}
