<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace IndexEngine\Controller;

use IndexEngine\Controller\Base\IndexEngineDriverConfigurationController as BaseIndexEngineDriverConfigurationController;

/**
 * Class IndexEngineDriverConfigurationController
 * @package IndexEngine\Controller
 */
class IndexEngineDriverConfigurationController extends BaseIndexEngineDriverConfigurationController
{
}
