<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace IndexEngine\Action\Base;

use IndexEngine\Model\Map\IndexEngineDriverConfigurationTableMap;
use IndexEngine\Event\IndexEngineDriverConfigurationEvent;
use IndexEngine\Event\IndexEngineDriverConfigurationEvents;
use IndexEngine\Model\IndexEngineDriverConfigurationQuery;
use IndexEngine\Model\IndexEngineDriverConfiguration;
use Thelia\Action\BaseAction;
use Thelia\Core\Event\ToggleVisibilityEvent;
use Thelia\Core\Event\UpdatePositionEvent;
use Propel\Runtime\Propel;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Thelia\Core\Event\TheliaEvents;
use \Thelia\Core\Event\TheliaFormEvent;

/**
 * Class IndexEngineDriverConfigurationAction
 * @package IndexEngine\Action
 * @author TheliaStudio
 */
class IndexEngineDriverConfigurationAction extends BaseAction implements EventSubscriberInterface
{
    public function create(IndexEngineDriverConfigurationEvent $event)
    {
        $this->createOrUpdate($event, new IndexEngineDriverConfiguration());
    }

    public function update(IndexEngineDriverConfigurationEvent $event)
    {
        $model = $this->getIndexEngineDriverConfiguration($event);

        $this->createOrUpdate($event, $model);
    }

    public function delete(IndexEngineDriverConfigurationEvent $event)
    {
        $this->getIndexEngineDriverConfiguration($event)->delete();
    }

    protected function createOrUpdate(IndexEngineDriverConfigurationEvent $event, IndexEngineDriverConfiguration $model)
    {
        $con = Propel::getConnection(IndexEngineDriverConfigurationTableMap::DATABASE_NAME);
        $con->beginTransaction();

        try {
            if (null !== $id = $event->getId()) {
                $model->setId($id);
            }

            if (null !== $driverCode = $event->getDriverCode()) {
                $model->setDriverCode($driverCode);
            }

            if (null !== $title = $event->getTitle()) {
                $model->setTitle($title);
            }

            if (null !== $serializedConfiguration = $event->getSerializedConfiguration()) {
                $model->setSerializedConfiguration($serializedConfiguration);
            }

            $model->save($con);

            $con->commit();
        } catch (\Exception $e) {
            $con->rollback();

            throw $e;
        }

        $event->setIndexEngineDriverConfiguration($model);
    }

    protected function getIndexEngineDriverConfiguration(IndexEngineDriverConfigurationEvent $event)
    {
        $model = IndexEngineDriverConfigurationQuery::create()->findPk($event->getId());

        if (null === $model) {
            throw new \RuntimeException(sprintf(
                "The 'index_engine_driver_configuration' id '%d' doesn't exist",
                $event->getId()
            ));
        }

        return $model;
    }

    public function beforeCreateFormBuild(TheliaFormEvent $event)
    {
    }

    public function beforeUpdateFormBuild(TheliaFormEvent $event)
    {
    }

    public function afterCreateFormBuild(TheliaFormEvent $event)
    {
    }

    public function afterUpdateFormBuild(TheliaFormEvent $event)
    {
    }

    /**
     * Returns an array of event names this subscriber wants to listen to.
     *
     * The array keys are event names and the value can be:
     *
     *  * The method name to call (priority defaults to 0)
     *  * An array composed of the method name to call and the priority
     *  * An array of arrays composed of the method names to call and respective
     *    priorities, or 0 if unset
     *
     * For instance:
     *
     *  * array('eventName' => 'methodName')
     *  * array('eventName' => array('methodName', $priority))
     *  * array('eventName' => array(array('methodName1', $priority), array('methodName2'))
     *
     * @return array The event names to listen to
     *
     * @api
     */
    public static function getSubscribedEvents()
    {
        return array(
            IndexEngineDriverConfigurationEvents::CREATE => array("create", 128),
            IndexEngineDriverConfigurationEvents::UPDATE => array("update", 128),
            IndexEngineDriverConfigurationEvents::DELETE => array("delete", 128),
            TheliaEvents::FORM_BEFORE_BUILD . ".index_engine_driver_configuration_create" => array("beforeCreateFormBuild", 128),
            TheliaEvents::FORM_BEFORE_BUILD . ".index_engine_driver_configuration_update" => array("beforeUpdateFormBuild", 128),
            TheliaEvents::FORM_AFTER_BUILD . ".index_engine_driver_configuration_create" => array("afterCreateFormBuild", 128),
            TheliaEvents::FORM_AFTER_BUILD . ".index_engine_driver_configuration_update" => array("afterUpdateFormBuild", 128),
        );
    }
}
